/**
 * Audit email delivery
 *
 * Sends the finished Score Boost Audit to the buyer with:
 * - Summary header (score, archetype, weakest phase)
 * - "View full audit" link back to /audit/[sessionId]
 * - MD file attached
 *
 * Non-blocking from the buyer's POV — the /audit page renders immediately.
 * Email is fire-and-forget; logs on failure but doesn't block the response.
 */

import { Resend } from 'resend';
import type { ScoreBoostAuditResult } from '@/prompts/score-boost-audit';
import { generateAuditMarkdown } from '@/lib/generate-audit-md';

const FROM_EMAIL = process.env.EMAIL_FROM || 'BrandOS <onboarding@resend.dev>';

export async function sendAuditEmail(params: {
  to: string;
  audit: ScoreBoostAuditResult;
  sessionId: string;
}): Promise<{ sent: boolean; error?: string }> {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    return { sent: false, error: 'RESEND_API_KEY not configured' };
  }

  const resend = new Resend(apiKey);
  const md = generateAuditMarkdown(params.audit);
  const appUrl =
    process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/, '') || 'https://mybrandos.app';
  const auditUrl = `${appUrl}/audit/${params.sessionId}`;
  const today = new Date().toISOString().slice(0, 10);
  const fileName = `brandos-audit-${params.audit.handle}-${today}.md`;

  const { audit } = params;

  const html = `<!DOCTYPE html>
<html>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:560px;margin:0 auto;padding:32px 24px;background:#ffffff;color:#111;">
  <p style="font-family:monospace;font-size:11px;text-transform:uppercase;letter-spacing:0.05em;color:#737373;margin:0 0 8px 0;">
    // score boost audit
  </p>
  <h1 style="font-size:24px;margin:0 0 24px 0;">@${audit.handle} — your audit is ready</h1>

  <div style="border:1px solid #e5e5e5;border-radius:6px;padding:20px;margin-bottom:24px;">
    <p style="margin:0;font-size:14px;color:#737373;">Your brand score</p>
    <p style="margin:4px 0 16px 0;font-size:40px;font-weight:bold;">${audit.overallScore}<span style="font-size:20px;color:#999;">/100</span></p>
    <p style="margin:0;font-size:14px;color:#737373;">Archetype</p>
    <p style="margin:4px 0 16px 0;font-size:18px;font-weight:600;">${audit.archetype.emoji} ${audit.archetype.name}</p>
    <p style="margin:0;font-size:14px;color:#737373;">Weakest phase</p>
    <p style="margin:4px 0 0 0;font-size:18px;font-weight:600;text-transform:uppercase;color:#b91c1c;">${audit.weakestPhase}</p>
  </div>

  <p style="font-size:15px;line-height:1.5;margin:0 0 20px 0;">${escapeHtml(audit.summary)}</p>

  <p style="margin:0 0 32px 0;">
    <a href="${auditUrl}" style="display:inline-block;background:#000;color:#fff;padding:12px 24px;border-radius:4px;text-decoration:none;font-size:14px;font-weight:500;">
      View full audit →
    </a>
  </p>

  <p style="font-size:13px;line-height:1.5;color:#737373;margin:0 0 12px 0;">
    The full audit includes a tweet-by-tweet breakdown with rewrites you can copy,
    your phase scores, and 3 specific actions for this week.
  </p>

  <p style="font-size:13px;line-height:1.5;color:#737373;margin:0 0 12px 0;">
    Your audit is also attached as a markdown file (<code>${fileName}</code>) —
    drop it into Claude or ChatGPT and use it as a voice guide when drafting tweets.
  </p>

  <hr style="border:none;border-top:1px solid #e5e5e5;margin:32px 0;" />

  <p style="font-family:monospace;font-size:11px;color:#999;margin:0;">
    Generated by BrandOS — mybrandos.app<br/>
    Your taste is your brand. See it. Sharpen it. Prove it.
  </p>
</body>
</html>`;

  try {
    const result = await resend.emails.send({
      from: FROM_EMAIL,
      to: params.to,
      subject: `Your BrandOS audit: ${audit.overallScore}/100 · @${audit.handle}`,
      html,
      attachments: [
        {
          filename: fileName,
          content: Buffer.from(md).toString('base64'),
        },
      ],
    });

    if (result.error) {
      console.error('[audit-email] Resend error:', result.error);
      return { sent: false, error: String(result.error) };
    }

    return { sent: true };
  } catch (err) {
    console.error('[audit-email] Send failed:', err);
    return { sent: false, error: (err as Error).message };
  }
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
