/**
 * Markdown generator for the Score Boost Audit.
 *
 * Produces the file the buyer downloads (and receives by email).
 * Spec lives in the Score Boost Audit build plan — keep this in sync.
 */

import type { ScoreBoostAuditResult } from '@/prompts/score-boost-audit';
import { statusEmoji } from '@/prompts/score-boost-audit';

export function generateAuditMarkdown(audit: ScoreBoostAuditResult): string {
  const date = new Date().toISOString().slice(0, 10);
  const { phaseScores: ps } = audit;

  const flaggedSection = audit.flaggedTweets
    .map(
      (t, i) => `#### Tweet ${i + 1}${i === 0 ? ' (Weakest)' : ''}
> ${t.original.replace(/\n/g, '\n> ')}

**Issue:** ${t.issue}
**Rewrite:**
> ${t.rewrite.replace(/\n/g, '\n> ')}
`
    )
    .join('\n');

  return `# BrandOS Score Boost Audit
## @${audit.handle} — ${date}

---

### Your Brand Score: ${audit.overallScore}/100

| Phase | Score | Status |
|-------|-------|--------|
| DEFINE | ${ps.define.score} | ${statusEmoji(ps.define.status)} |
| CHECK | ${ps.check.score} | ${statusEmoji(ps.check.status)} |
| GENERATE | ${ps.generate.score} | ${statusEmoji(ps.generate.status)} |
| SCALE | ${ps.scale.score} | ${statusEmoji(ps.scale.status)} |

**DEFINE.** ${ps.define.insight}

**CHECK.** ${ps.check.insight}

**GENERATE.** ${ps.generate.insight}

**SCALE.** ${ps.scale.insight}

---

### Your Archetype: ${audit.archetype.emoji} ${audit.archetype.name}

${audit.archetype.description}

**Strengths:**
${audit.archetype.strengths.map((s) => `- ${s}`).join('\n')}

**Misalignments:**
${audit.archetype.misalignments.map((m) => `- ${m}`).join('\n')}

---

### Tweet-by-Tweet Analysis

${flaggedSection}

---

### Top 3 Actions This Week

${audit.topActions.map((a, i) => `${i + 1}. ${a}`).join('\n')}

---

### Summary

${audit.summary}

---

### How to Use This File with AI

Drop this file into ChatGPT, Claude, or your favorite AI tool
and use these prompts:

**Generate on-brand tweets:**
"Using the attached brand audit as my voice guide, write 5 tweets
about {topic}. Match my archetype and fix the weaknesses identified
in the audit."

**Rewrite off-brand drafts:**
"Here's a draft tweet: {paste draft}. Using my brand audit file,
rewrite it to be on-brand. Explain what you changed and why."

**Weekly brand check-in:**
"Based on my brand audit, score these 3 tweets I posted this week
on a 1-100 scale. Tell me if I'm improving on the gaps identified."

**Content calendar:**
"Using my archetype (${audit.archetype.name}) and the action items
from my brand audit, create a 7-day content calendar with 2 tweets
per day. Each tweet should target my weakest phase: ${audit.weakestPhase.toUpperCase()}."

---

*Generated by BrandOS — mybrandos.app*
*Your taste is your brand. See it. Sharpen it. Prove it.*
`;
}
