declare module '@/lib/gsap/ScrollTrigger' {
  export const ScrollTrigger: {
    (vars: any, animation?: any): void;
    register(core: any): any;
    defaults(config: any): { toggleActions: string; anticipatePin: number };
    disable(reset?: any, kill?: any): void;
    enable(): void;
    refresh(safe?: boolean): void;
    update(force?: boolean): void;
    clearScrollMemory(): void;
    maxScroll(element: Element, horizontal?: boolean): number;
    getScrollFunc(element: Element, horizontal?: boolean): () => number;
    getById(id: string): any;
    getAll(): any[];
    isScrolling(): boolean;
    addEventListener(type: string, callback: Function): void;
    removeEventListener(type: string, callback: Function): void;
    batch(targets: any, vars: any): any[];
    sort(func?: Function): any[];
    observe(vars: any): any;
    normalizeScroll(config?: any): any;
    core: any;
    isTouch: number;
    isInViewport(element: Element, ratio?: number, horizontal?: boolean): boolean;
    positionInViewport(element: Element, referencePoint?: string, horizontal?: boolean): number;
    killAll(allowListeners?: any): void;
    create(vars: {
      trigger?: Element | string;
      start?: string | number | Function;
      end?: string | number | Function;
      pin?: boolean | Element | string;
      pinSpacing?: boolean | string;
      scrub?: boolean | number;
      onUpdate?: (self: any) => void;
      onEnter?: (self: any) => void;
      onLeave?: (self: any) => void;
      onEnterBack?: (self: any) => void;
      onLeaveBack?: (self: any) => void;
      onToggle?: (self: any) => void;
      onRefresh?: (self: any) => void;
      markers?: boolean | object;
      id?: string;
      toggleClass?: string | object;
      toggleActions?: string;
      anticipatePin?: number;
      fastScrollEnd?: boolean | number;
      preventOverlaps?: boolean | string;
      containerAnimation?: any;
      horizontal?: boolean;
      invalidateOnRefresh?: boolean;
      refreshPriority?: number;
      snap?: number | number[] | Function | object;
      pinReparent?: boolean;
      pinSpacer?: Element | string;
      endTrigger?: Element | string;
      once?: boolean;
      scroller?: Element | string | Window;
      [key: string]: any;
    }): {
      kill(revert?: boolean, allowAnimation?: boolean): void;
      enable(reset?: boolean, refresh?: boolean): any;
      disable(revert?: boolean, allowAnimation?: boolean): any;
      refresh(): any;
      update(reset?: boolean): any;
      progress: number;
      direction: number;
      isActive: boolean;
      vars: any;
      start: number;
      end: number;
      trigger: Element;
      pin: Element;
      animation: any;
      scroller: Element | Window;
      scroll: number;
      getVelocity(): number;
      labelToScroll(label: string): number;
      previous(): any;
      next(): any;
    };
  };
}
