/**
 * Export Bridge for Remotion
 * Exports captured screenshots for video composition
 */

import { getSessionScreenshots } from './storage';
import { JOURNEY_MOMENTS } from './moments';

export interface ExportManifest {
  sessionId: string;
  exportedAt: number;
  totalFrames: number;
  fps: number;
  width: number;
  height: number;
  screenshots: ExportedScreenshot[];
}

export interface ExportedScreenshot {
  filename: string;
  momentId: string;
  label: string;
  startFrame: number;
  duration: number;
  transition: 'fade' | 'zoom' | 'slide';
  order: number;
}

const FPS = 30;
const OUTPUT_WIDTH = 1920;
const OUTPUT_HEIGHT = 1080;

/**
 * Generate export manifest for Remotion
 */
export async function generateExportManifest(sessionId: string): Promise<ExportManifest> {
  const screenshots = await getSessionScreenshots(sessionId);

  // Sort by moment order
  const sortedScreenshots = [...screenshots].sort((a, b) => {
    const aIndex = JOURNEY_MOMENTS.findIndex(m => m.id === a.momentId);
    const bIndex = JOURNEY_MOMENTS.findIndex(m => m.id === b.momentId);
    return aIndex - bIndex;
  });

  let currentFrame = 0;
  const exportedScreenshots: ExportedScreenshot[] = sortedScreenshots.map((screenshot, index) => {
    const moment = screenshot.moment;
    const exported: ExportedScreenshot = {
      filename: `${String(index).padStart(3, '0')}-${screenshot.momentId.replace(/:/g, '-')}.png`,
      momentId: screenshot.momentId,
      label: moment.label,
      startFrame: currentFrame,
      duration: moment.duration,
      transition: moment.transition,
      order: index,
    };
    currentFrame += moment.duration;
    return exported;
  });

  return {
    sessionId,
    exportedAt: Date.now(),
    totalFrames: currentFrame + 60, // Add 2 second outro
    fps: FPS,
    width: OUTPUT_WIDTH,
    height: OUTPUT_HEIGHT,
    screenshots: exportedScreenshots,
  };
}

/**
 * Convert screenshots to downloadable zip (for manual export)
 */
export async function exportAsZip(sessionId: string): Promise<Blob> {
  const screenshots = await getSessionScreenshots(sessionId);
  const manifest = await generateExportManifest(sessionId);

  // Use JSZip if available, otherwise create individual downloads
  // For simplicity, we'll create a JSON manifest and trigger individual downloads
  const files: { name: string; content: Blob | string }[] = [];

  // Add manifest
  files.push({
    name: 'manifest.json',
    content: JSON.stringify(manifest, null, 2),
  });

  // Add screenshots
  screenshots.forEach((screenshot, index) => {
    const filename = manifest.screenshots[index]?.filename || `${index}.png`;
    // Convert data URL to blob
    const arr = screenshot.dataUrl.split(',');
    const mime = arr[0].match(/:(.*?);/)?.[1] || 'image/png';
    const bstr = atob(arr[1]);
    let n = bstr.length;
    const u8arr = new Uint8Array(n);
    while (n--) {
      u8arr[n] = bstr.charCodeAt(n);
    }
    files.push({
      name: `captures/${filename}`,
      content: new Blob([u8arr], { type: mime }),
    });
  });

  // Create a simple text file listing all exports (fallback without JSZip)
  const listing = files.map(f => f.name).join('\n');
  return new Blob([listing], { type: 'text/plain' });
}

/**
 * Generate TypeScript data file for Remotion
 * This creates a file that can be imported directly by the Remotion composition
 */
export async function generateRemotionDataFile(sessionId: string): Promise<string> {
  const screenshots = await getSessionScreenshots(sessionId);
  const manifest = await generateExportManifest(sessionId);

  // Create inline base64 data for each screenshot
  const screenshotData = screenshots.map((screenshot, index) => {
    const meta = manifest.screenshots[index];
    return {
      ...meta,
      dataUrl: screenshot.dataUrl,
    };
  });

  const code = `// Auto-generated by BrandOS Demo Capture
// Session: ${sessionId}
// Generated: ${new Date().toISOString()}

export const SHOWCASE_CONFIG = {
  fps: ${FPS},
  width: ${OUTPUT_WIDTH},
  height: ${OUTPUT_HEIGHT},
  totalFrames: ${manifest.totalFrames},
};

export const SHOWCASE_SCREENSHOTS = ${JSON.stringify(screenshotData, null, 2)};

export type ShowcaseScreenshot = typeof SHOWCASE_SCREENSHOTS[number];
`;

  return code;
}

/**
 * Download manifest as JSON
 */
export function downloadManifest(manifest: ExportManifest): void {
  const blob = new Blob([JSON.stringify(manifest, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `brandos-demo-${manifest.sessionId}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Download all screenshots as individual files
 */
export async function downloadAllScreenshots(sessionId: string): Promise<void> {
  const screenshots = await getSessionScreenshots(sessionId);
  const manifest = await generateExportManifest(sessionId);

  // Download each screenshot with a delay to prevent browser blocking
  for (let i = 0; i < screenshots.length; i++) {
    const screenshot = screenshots[i];
    const filename = manifest.screenshots[i]?.filename || `${i}.png`;

    const link = document.createElement('a');
    link.href = screenshot.dataUrl;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    // Small delay between downloads
    await new Promise(resolve => setTimeout(resolve, 200));
  }
}

/**
 * Copy Remotion data to clipboard
 */
export async function copyRemotionDataToClipboard(sessionId: string): Promise<void> {
  const code = await generateRemotionDataFile(sessionId);
  await navigator.clipboard.writeText(code);
}

/**
 * Get export statistics
 */
export function getExportStats(manifest: ExportManifest): {
  totalScreenshots: number;
  totalDuration: string;
  estimatedFileSize: string;
} {
  const durationSeconds = manifest.totalFrames / manifest.fps;
  const minutes = Math.floor(durationSeconds / 60);
  const seconds = Math.round(durationSeconds % 60);

  return {
    totalScreenshots: manifest.screenshots.length,
    totalDuration: minutes > 0 ? `${minutes}m ${seconds}s` : `${seconds}s`,
    estimatedFileSize: `~${Math.round(manifest.screenshots.length * 0.5)}MB`, // Rough estimate
  };
}
