import { BrandKitAssets } from '@/lib/brandKitStore';
import { BrandDNA } from '@/lib/types';

// Export brand kit as JSON
export function exportAsJSON(brandDNA: BrandDNA, brandKit: BrandKitAssets): string {
  const exportData = {
    version: '1.0',
    exportedAt: new Date().toISOString(),
    brand: {
      name: brandDNA.name,
      colors: brandDNA.colors,
      tone: brandDNA.tone,
      keywords: brandDNA.keywords,
      doPatterns: brandDNA.doPatterns,
      dontPatterns: brandDNA.dontPatterns,
    },
    brandKit: {
      logos: brandKit.logos.map((l) => ({
        name: l.name,
        type: l.type,
        clearSpace: l.clearSpace,
        minSize: l.minSize,
        usageNotes: l.usageNotes,
      })),
      colors: brandKit.extendedColors.map((c) => ({
        name: c.name,
        hex: c.hex,
        category: c.category,
        usage: c.usage,
      })),
      typography: {
        fonts: brandKit.typography.fonts.map((f) => ({
          name: f.name,
          family: f.family,
          category: f.category,
          weights: f.weights,
        })),
        pairing: brandKit.typography.pairing,
        scale: brandKit.typography.scale,
      },
      imagery: brandKit.imagery.map((i) => ({
        name: i.name,
        type: i.type,
        category: i.category,
        tags: i.tags,
        doExample: i.doExample,
        dontExample: i.dontExample,
      })),
      icons: brandKit.icons.map((i) => ({
        name: i.name,
        category: i.category,
        style: i.style,
        sizes: i.sizes,
      })),
      templates: brandKit.templates.map((t) => ({
        name: t.name,
        type: t.type,
        platform: t.platform,
        dimensions: t.dimensions,
      })),
    },
  };

  return JSON.stringify(exportData, null, 2);
}

// Download JSON file
export function downloadJSON(brandDNA: BrandDNA, brandKit: BrandKitAssets) {
  const json = exportAsJSON(brandDNA, brandKit);
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${brandDNA.name.toLowerCase().replace(/\s+/g, '-')}-brand-kit.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// Generate PDF content structure (for use with a PDF library)
export function generatePDFContent(brandDNA: BrandDNA, brandKit: BrandKitAssets) {
  return {
    title: `${brandDNA.name} Brand Kit`,
    sections: [
      {
        title: 'Brand Overview',
        content: {
          name: brandDNA.name,
          keywords: brandDNA.keywords,
          doPatterns: brandDNA.doPatterns,
          dontPatterns: brandDNA.dontPatterns,
        },
      },
      {
        title: 'Color Palette',
        content: {
          primary: brandDNA.colors,
          extended: brandKit.extendedColors,
        },
      },
      {
        title: 'Typography',
        content: {
          fonts: brandKit.typography.fonts,
          pairing: brandKit.typography.pairing,
          scale: brandKit.typography.scale,
        },
      },
      {
        title: 'Logos & Marks',
        content: {
          logos: brandKit.logos,
        },
      },
      {
        title: 'Tone & Voice',
        content: {
          tone: brandDNA.tone,
          voiceSamples: brandDNA.voiceSamples,
        },
      },
    ],
  };
}

// Create ZIP file structure
export async function createZIPStructure(brandDNA: BrandDNA, brandKit: BrandKitAssets) {
  const structure = {
    'README.md': generateReadme(brandDNA, brandKit),
    'brand-kit.json': exportAsJSON(brandDNA, brandKit),
    'colors.css': generateColorCSS(brandDNA, brandKit),
    'typography.css': generateTypographyCSS(brandKit),
  };

  return structure;
}

// Generate README
function generateReadme(brandDNA: BrandDNA, brandKit: BrandKitAssets): string {
  return `# ${brandDNA.name} Brand Kit

## Overview
This brand kit contains all the essential assets and guidelines for ${brandDNA.name}.

## Contents
- **Colors**: ${brandKit.extendedColors.length} colors defined
- **Typography**: ${brandKit.typography.fonts.length} font(s) configured
- **Logos**: ${brandKit.logos.length} logo variant(s)
- **Icons**: ${brandKit.icons.length} icon(s)
- **Templates**: ${brandKit.templates.length} template(s)

## Brand Keywords
${brandDNA.keywords.map((k) => `- ${k}`).join('\n')}

## Color Palette
${brandKit.extendedColors.map((c) => `- **${c.name}**: ${c.hex} (${c.category})`).join('\n')}

## Typography
Heading Font: ${brandKit.typography.pairing.heading}
Body Font: ${brandKit.typography.pairing.body}

## Usage Guidelines

### Do
${brandDNA.doPatterns.map((p) => `- ${p}`).join('\n')}

### Don't
${brandDNA.dontPatterns.map((p) => `- ${p}`).join('\n')}

---
Generated by BrandOS
`;
}

// Generate CSS variables for colors
function generateColorCSS(brandDNA: BrandDNA, brandKit: BrandKitAssets): string {
  const lines = [
    '/* Brand Colors - Generated by BrandOS */',
    ':root {',
    `  /* Primary Colors */`,
    `  --color-primary: ${brandDNA.colors.primary};`,
    `  --color-secondary: ${brandDNA.colors.secondary};`,
    `  --color-accent: ${brandDNA.colors.accent};`,
    '',
    '  /* Extended Palette */',
  ];

  brandKit.extendedColors.forEach((color) => {
    const varName = color.name.toLowerCase().replace(/\s+/g, '-');
    lines.push(`  --color-${varName}: ${color.hex}; /* ${color.usage || color.category} */`);
  });

  lines.push('}');

  return lines.join('\n');
}

// Generate CSS for typography
function generateTypographyCSS(brandKit: BrandKitAssets): string {
  const lines = [
    '/* Typography - Generated by BrandOS */',
    '',
    '/* Font Families */',
    ':root {',
    `  --font-heading: "${brandKit.typography.pairing.heading}", sans-serif;`,
    `  --font-body: "${brandKit.typography.pairing.body}", sans-serif;`,
  ];

  if (brandKit.typography.pairing.accent) {
    lines.push(`  --font-accent: "${brandKit.typography.pairing.accent}", sans-serif;`);
  }

  lines.push('}', '', '/* Type Scale */');

  brandKit.typography.scale.forEach((style) => {
    const className = style.name.toLowerCase().replace(/\s+/g, '-');
    lines.push(`
.${className} {
  font-size: ${style.fontSize};
  line-height: ${style.lineHeight};
  font-weight: ${style.fontWeight};
  letter-spacing: ${style.letterSpacing};
}`);
  });

  return lines.join('\n');
}

// Simple ZIP download (creates a downloadable with file content)
export function downloadAsZIP(brandDNA: BrandDNA, brandKit: BrandKitAssets) {
  // For now, download as a combined text file
  // In production, use JSZip library
  const content = `
=== ${brandDNA.name} Brand Kit ===

${generateReadme(brandDNA, brandKit)}

=== colors.css ===
${generateColorCSS(brandDNA, brandKit)}

=== typography.css ===
${generateTypographyCSS(brandKit)}

=== brand-kit.json ===
${exportAsJSON(brandDNA, brandKit)}
`;

  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${brandDNA.name.toLowerCase().replace(/\s+/g, '-')}-brand-kit.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}








