'use client';

import { useState } from 'react';
import { useCurrentBrand, useBrandStore } from '@/lib/store';
import { useExportStore } from '@/lib/exportStore';
import { PitchSlide } from '@/lib/types';

export default function ExportCenter() {
  const brandDNA = useCurrentBrand();
  const { history } = useBrandStore();
  const { generatedContent, savedConcepts, toggleApproval, removeContent } = useExportStore();
  
  const [isGenerating, setIsGenerating] = useState(false);
  const [activeExport, setActiveExport] = useState<'brand-kit' | 'pitch-deck' | null>(null);
  const [pitchSlides, setPitchSlides] = useState<PitchSlide[]>([]);
  const [includeConcepts, setIncludeConcepts] = useState(true);
  const [error, setError] = useState('');

  const approvedCount = generatedContent.filter(c => c.approved).length;
  const checkHistory = history.filter(h => h.type === 'check');
  const generateHistory = history.filter(h => h.type === 'generate');

  const generateBrandKit = async () => {
    if (!brandDNA?.name) return;
    
    setIsGenerating(true);
    setActiveExport('brand-kit');
    setError('');

    try {
      const response = await fetch('/api/export/brand-kit', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          brandDNA,
          visualConcepts: includeConcepts ? savedConcepts : [],
          generatedContent: generatedContent.filter(c => c.approved),
        }),
      });

      const data = await response.json();
      
      if (!response.ok) throw new Error(data.error);

      // Open in new window for printing/saving as PDF
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(data.html);
        printWindow.document.close();
        // Auto-trigger print dialog after a short delay
        setTimeout(() => printWindow.print(), 500);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate brand kit');
    }

    setIsGenerating(false);
  };

  const generatePitchDeck = async () => {
    if (!brandDNA?.name) return;
    
    setIsGenerating(true);
    setActiveExport('pitch-deck');
    setError('');

    try {
      const response = await fetch('/api/export/pitch-deck', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          brandDNA,
          visualConcepts: includeConcepts ? savedConcepts : [],
          includeMetrics: true,
        }),
      });

      const data = await response.json();
      
      if (!response.ok) throw new Error(data.error);

      setPitchSlides(data.slides);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate pitch deck');
    }

    setIsGenerating(false);
  };

  const downloadPitchDeckHTML = () => {
    if (!brandDNA) return;
    
    const html = generatePitchDeckHTML(pitchSlides, brandDNA);
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${brandDNA.name.replace(/\s+/g, '_')}_pitch_deck.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const copyOnePager = () => {
    if (!brandDNA) return;
    
    const text = `
${brandDNA.name.toUpperCase()} BRAND SUMMARY
${'='.repeat(40)}

COLORS
Primary: ${brandDNA.colors.primary}
Secondary: ${brandDNA.colors.secondary}
Accent: ${brandDNA.colors.accent}

TONE PROFILE
Minimal: ${brandDNA.tone.minimal}/100
Playful: ${brandDNA.tone.playful}/100
Bold: ${brandDNA.tone.bold}/100
Experimental: ${brandDNA.tone.experimental}/100

KEYWORDS
${brandDNA.keywords.join(', ') || 'None defined'}

VOICE SAMPLES
${brandDNA.voiceSamples.map(s => `"${s}"`).join('\n') || 'None defined'}

DO's
${brandDNA.doPatterns.map(p => `✓ ${p}`).join('\n') || 'None defined'}

DON'Ts
${brandDNA.dontPatterns.map(p => `✗ ${p}`).join('\n') || 'None defined'}

${'='.repeat(40)}
Generated by Brandos • ${new Date().toLocaleDateString()}
    `.trim();
    
    navigator.clipboard.writeText(text);
  };

  if (!brandDNA?.name) {
    return (
      <div className="text-center py-16">
        <div className="text-4xl mb-4">📦</div>
        <h3 className="text-lg font-medium mb-2">Set up your Brand DNA first</h3>
        <p className="text-muted">You need brand data before you can export</p>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      {/* Brand Summary */}
      <div className="bg-surface rounded-xl p-6">
        <h3 className="text-xs uppercase tracking-widest text-muted mb-4">What&apos;s Included</h3>
        <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
          <div className="text-center p-4 bg-background rounded-lg border border-border">
            <div className="text-2xl font-light">{brandDNA.keywords.length}</div>
            <div className="text-xs text-muted">Keywords</div>
          </div>
          <div className="text-center p-4 bg-background rounded-lg border border-border">
            <div className="text-2xl font-light">{brandDNA.voiceSamples.length}</div>
            <div className="text-xs text-muted">Voice Samples</div>
          </div>
          <div className="text-center p-4 bg-background rounded-lg border border-border">
            <div className="text-2xl font-light">{savedConcepts.length}</div>
            <div className="text-xs text-muted">Visual Concepts</div>
          </div>
          <div className="text-center p-4 bg-background rounded-lg border border-border">
            <div className="text-2xl font-light">{checkHistory.length}</div>
            <div className="text-xs text-muted">Checks</div>
          </div>
          <div className="text-center p-4 bg-background rounded-lg border border-border">
            <div className="text-2xl font-light">{approvedCount}</div>
            <div className="text-xs text-muted">Approved</div>
          </div>
        </div>
      </div>

      {/* Saved Visual Concepts Preview */}
      {savedConcepts.length > 0 && (
        <div className="bg-surface rounded-xl p-6">
          <h3 className="text-xs uppercase tracking-widest text-muted mb-4">
            Visual Concepts ({savedConcepts.length})
          </h3>
          <p className="text-sm text-muted mb-4">
            These will be included in your Brand Kit PDF with images and design directions.
          </p>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {savedConcepts.map((concept, i) => (
              <div key={i} className="bg-background rounded-lg overflow-hidden border border-border">
                {concept.imageUrl && (
                  <img
                    src={concept.imageUrl}
                    alt={concept.title}
                    className="w-full h-24 object-cover"
                  />
                )}
                <div className="p-3">
                  <h4 className="text-sm font-medium truncate">{concept.title}</h4>
                  <div className="flex gap-1 mt-2">
                    {concept.colorPalette.slice(0, 4).map((c, ci) => (
                      <div
                        key={ci}
                        className="w-4 h-4 rounded-full border border-border"
                        style={{ backgroundColor: c }}
                      />
                    ))}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Export Options */}
      <div className="grid md:grid-cols-2 gap-6">
        {/* Brand Kit */}
        <div className="bg-surface rounded-xl p-6">
          <div className="flex items-start justify-between mb-4">
            <div>
              <h3 className="font-medium text-lg">Brand Kit</h3>
              <p className="text-sm text-muted">Comprehensive PDF guidelines</p>
            </div>
            <span className="px-2 py-1 bg-background border border-border rounded text-xs">PDF</span>
          </div>
          
          <div className="space-y-3 mb-6 text-sm">
            <div className="flex items-center gap-2">
              <span className="text-green-500">✓</span>
              <span className="text-muted">Color palette & usage</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-green-500">✓</span>
              <span className="text-muted">Tone profile visualization</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-green-500">✓</span>
              <span className="text-muted">Voice guidelines & samples</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-green-500">✓</span>
              <span className="text-muted">Do&apos;s and Don&apos;ts</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-green-500">✓</span>
              <span className="text-muted">Visual concepts</span>
            </div>
          </div>

          <button
            onClick={generateBrandKit}
            disabled={isGenerating}
            className="w-full py-3 bg-foreground text-background rounded-full font-medium hover:opacity-80 disabled:opacity-30 transition-opacity"
          >
            {isGenerating && activeExport === 'brand-kit' ? 'Generating...' : 'Generate Brand Kit'}
          </button>
        </div>

        {/* Pitch Deck */}
        <div className="bg-surface rounded-xl p-6">
          <div className="flex items-start justify-between mb-4">
            <div>
              <h3 className="font-medium text-lg">Pitch Deck</h3>
              <p className="text-sm text-muted">AI-generated presentation</p>
            </div>
            <span className="px-2 py-1 bg-background border border-border rounded text-xs">HTML</span>
          </div>
          
          <div className="space-y-3 mb-4 text-sm">
            <div className="flex items-center gap-2">
              <span className="text-green-500">✓</span>
              <span className="text-muted">Brand story & positioning</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-green-500">✓</span>
              <span className="text-muted">Visual identity showcase</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-green-500">✓</span>
              <span className="text-muted">Voice & tone examples</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-green-500">✓</span>
              <span className="text-muted">Color system breakdown</span>
            </div>
          </div>

          {/* Options */}
          <div className="mb-6">
            <label className="flex items-center gap-2 text-sm cursor-pointer">
              <input
                type="checkbox"
                checked={includeConcepts}
                onChange={(e) => setIncludeConcepts(e.target.checked)}
                className="rounded bg-background border-border"
              />
              <span className="text-muted">Include visual concepts</span>
            </label>
          </div>

          <button
            onClick={generatePitchDeck}
            disabled={isGenerating}
            className="w-full py-3 bg-foreground text-background rounded-full font-medium hover:opacity-80 disabled:opacity-30 transition-opacity"
          >
            {isGenerating && activeExport === 'pitch-deck' ? 'Generating...' : 'Generate Pitch Deck'}
          </button>
        </div>
      </div>

      {error && (
        <div className="p-4 border border-red-500/20 bg-red-500/5 rounded-lg">
          <p className="text-sm text-red-500">{error}</p>
        </div>
      )}

      {/* Pitch Deck Preview */}
      {pitchSlides.length > 0 && (
        <div className="bg-surface rounded-xl p-6 animate-fade-in">
          <div className="flex items-center justify-between mb-6">
            <h3 className="text-xs uppercase tracking-widest text-muted">Pitch Deck Preview</h3>
            <button
              onClick={downloadPitchDeckHTML}
              className="px-4 py-2 bg-foreground text-background rounded-full text-sm font-medium hover:opacity-80 transition-opacity"
            >
              Download HTML
            </button>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {pitchSlides.map((slide) => (
              <div
                key={slide.slideNumber}
                className="aspect-video bg-background rounded-lg p-4 relative overflow-hidden border border-border"
                style={{
                  background: slide.type === 'title' 
                    ? brandDNA.colors.primary 
                    : undefined
                }}
              >
                <div className="absolute top-2 left-2 text-xs text-muted">
                  {slide.slideNumber}
                </div>
                
                {slide.type === 'title' && (
                  <div className="h-full flex flex-col justify-center items-center text-center">
                    <div className="font-medium text-sm" style={{ color: brandDNA.colors.secondary }}>
                      {slide.headline}
                    </div>
                    {slide.subheadline && (
                      <div className="text-xs mt-1 opacity-70" style={{ color: brandDNA.colors.secondary }}>
                        {slide.subheadline}
                      </div>
                    )}
                  </div>
                )}

                {slide.type === 'content' && (
                  <div className="h-full flex flex-col pt-4">
                    <div className="font-medium text-xs mb-2 truncate">{slide.headline}</div>
                    <div className="space-y-1 overflow-hidden">
                      {slide.bullets?.slice(0, 3).map((bullet, i) => (
                        <div key={i} className="text-[10px] text-muted truncate">
                          • {bullet}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {slide.type === 'quote' && (
                  <div className="h-full flex items-center justify-center">
                    <div className="text-[10px] text-center italic text-muted line-clamp-3">
                      &ldquo;{slide.quote}&rdquo;
                    </div>
                  </div>
                )}

                {slide.type === 'colors' && (
                  <div className="h-full flex flex-col justify-center items-center gap-2">
                    <div className="text-xs mb-2">{slide.headline}</div>
                    <div className="flex gap-2">
                      <div className="w-6 h-6 rounded-full border border-border" style={{ background: brandDNA.colors.primary }} />
                      <div className="w-6 h-6 rounded-full border border-border" style={{ background: brandDNA.colors.secondary }} />
                      <div className="w-6 h-6 rounded-full border border-border" style={{ background: brandDNA.colors.accent }} />
                    </div>
                  </div>
                )}

                {slide.type === 'stats' && (
                  <div className="h-full flex flex-col justify-center pt-2">
                    <div className="font-medium text-xs mb-2 truncate">{slide.headline}</div>
                    <div className="flex gap-3 justify-center">
                      {slide.stats?.slice(0, 2).map((stat, i) => (
                        <div key={i} className="text-center">
                          <div className="font-medium text-sm" style={{ color: brandDNA.colors.accent }}>
                            {stat.value}
                          </div>
                          <div className="text-[8px] text-muted">{stat.label}</div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {slide.type === 'closing' && (
                  <div className="h-full flex flex-col justify-center items-center text-center">
                    <div className="font-medium text-xs">{slide.headline}</div>
                    {slide.subheadline && (
                      <div className="text-[10px] text-muted mt-1">{slide.subheadline}</div>
                    )}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Quick One-Pager */}
      <div className="bg-surface rounded-xl p-6">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="font-medium">Quick One-Pager</h3>
            <p className="text-sm text-muted">Single-page brand summary as text</p>
          </div>
          <button
            onClick={copyOnePager}
            className="px-4 py-2 bg-background border border-border text-foreground rounded-full text-sm hover:bg-surface transition-colors"
          >
            Copy to Clipboard
          </button>
        </div>
      </div>

      {/* Content Library */}
      {generatedContent.length > 0 && (
        <div className="bg-surface rounded-xl p-6">
          <h3 className="text-xs uppercase tracking-widest text-muted mb-4">
            Content Library ({generatedContent.length})
          </h3>
          <p className="text-sm text-muted mb-4">
            Toggle approval to include content in exports.
          </p>
          <div className="space-y-3">
            {generatedContent.map((item) => (
              <div key={item.id} className="flex items-start gap-3 p-4 bg-background rounded-lg border border-border">
                <button
                  onClick={() => toggleApproval(item.id)}
                  className={`w-6 h-6 rounded-full border-2 flex items-center justify-center flex-shrink-0 transition-colors ${
                    item.approved 
                      ? 'bg-green-500 border-green-500 text-white' 
                      : 'border-border hover:border-muted'
                  }`}
                >
                  {item.approved && '✓'}
                </button>
                <div className="flex-1 min-w-0">
                  <div className="text-xs text-muted uppercase mb-1">
                    {item.type}{item.platform ? ` • ${item.platform}` : ''}
                  </div>
                  <p className="text-sm truncate">{item.content}</p>
                </div>
                <button
                  onClick={() => removeContent(item.id)}
                  className="text-muted hover:text-foreground transition-colors"
                >
                  ×
                </button>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// Helper function to generate pitch deck HTML
function generatePitchDeckHTML(slides: PitchSlide[], brandDNA: any): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${brandDNA.name} Pitch Deck</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
    
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', -apple-system, sans-serif; background: #000; }
    
    .slide {
      width: 100vw;
      height: 100vh;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      padding: 10%;
      page-break-after: always;
    }
    
    .slide.title { background: ${brandDNA.colors.primary}; color: ${brandDNA.colors.secondary}; }
    .slide.content { background: #111; color: #fff; }
    .slide.closing { background: ${brandDNA.colors.accent}; color: #fff; }
    
    h1 { font-size: 4rem; margin-bottom: 1rem; font-weight: 700; letter-spacing: -0.02em; }
    h2 { font-size: 2.5rem; margin-bottom: 2rem; font-weight: 600; }
    p { font-size: 1.5rem; opacity: 0.8; }
    ul { list-style: none; font-size: 1.25rem; }
    li { padding: 0.75rem 0; }
    li::before { content: "→ "; opacity: 0.5; }
    
    .quote { font-size: 2rem; font-style: italic; max-width: 800px; text-align: center; line-height: 1.4; }
    
    .colors { display: flex; gap: 24px; margin-top: 32px; }
    .color-dot { width: 80px; height: 80px; border-radius: 50%; }
    
    .stat { text-align: center; padding: 0 48px; }
    .stat-value { font-size: 4rem; font-weight: 700; color: ${brandDNA.colors.accent}; }
    .stat-label { font-size: 1rem; opacity: 0.7; margin-top: 8px; }
    
    @media print {
      .slide { page-break-inside: avoid; }
    }
  </style>
</head>
<body>
${slides.map(slide => {
  if (slide.type === 'title') {
    return `<div class="slide title">
      <h1>${slide.headline}</h1>
      ${slide.subheadline ? `<p>${slide.subheadline}</p>` : ''}
    </div>`;
  }
  if (slide.type === 'content') {
    return `<div class="slide content">
      <h2>${slide.headline}</h2>
      <ul>${slide.bullets?.map(b => `<li>${b}</li>`).join('') || ''}</ul>
    </div>`;
  }
  if (slide.type === 'quote') {
    return `<div class="slide content">
      <p class="quote">"${slide.quote}"</p>
    </div>`;
  }
  if (slide.type === 'colors') {
    return `<div class="slide content">
      <h2>${slide.headline || 'Color System'}</h2>
      <div class="colors">
        <div class="color-dot" style="background: ${brandDNA.colors.primary}"></div>
        <div class="color-dot" style="background: ${brandDNA.colors.secondary}"></div>
        <div class="color-dot" style="background: ${brandDNA.colors.accent}"></div>
      </div>
    </div>`;
  }
  if (slide.type === 'stats') {
    return `<div class="slide content">
      <h2>${slide.headline}</h2>
      <div style="display: flex; gap: 4rem; margin-top: 2rem;">
        ${slide.stats?.map(s => `
          <div class="stat">
            <div class="stat-value">${s.value}</div>
            <div class="stat-label">${s.label}</div>
          </div>
        `).join('') || ''}
      </div>
    </div>`;
  }
  if (slide.type === 'closing') {
    return `<div class="slide closing">
      <h1>${slide.headline}</h1>
      ${slide.subheadline ? `<p>${slide.subheadline}</p>` : ''}
    </div>`;
  }
  return '';
}).join('\n')}
</body>
</html>
  `.trim();
}

